version: '3.8'
services:
  app:
    image: news-dashboard
    ports:
      - "8000:8000"
    env_file:
      - src/app/.env
    depends_on:
      - db
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: boywithuke
      POSTGRES_DB: news-dashboard
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  postgres_data: